version: '3.8'

services:
  db:
    container_name: ${PSQL_HOST}
    image: postgres:15.1
    environment:
      POSTGRES_DB: ${PSQL_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgsql_data:/var/lib/postgresql/data/
    networks:
      - uf_network

  backend:
    container_name: uf_backend
    build: ./
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - uf_network

volumes:
  pgsql_data:

networks:
  uf_network:
    name: uf_network
    driver: bridge
